services:
#    blog.example:
#        class: Blogger\BlogBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]


    blog.markdown:
      class: Blogger\BlogBundle\Service\MarkdownTransformer
      arguments: ["@markdown.parser"]

